name: falzar-commons
version: 0.1.0.0
github: "aleperaltabazas/falzar-commons"
license: BSD3
author: "Alejandro Martín Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2023 Alejandro Martín Peralta Bazas"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/aleperaltabazas/falzar-commons#readme>

dependencies:
  - aeson <= 2.1.2.1
  - base >= 4.7 && < 5
  - haskell-commons
  - http-types <= 0.12.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - QuasiQuotes
  - DeriveGeneric
  - OverloadedRecordDot

library:
  source-dirs: src

tests:
  falzar-commons-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - falzar-commons
