name: falzar-daemon
version: 0.1.0.0
github: "aleperaltabazas/falzar"
license: BSD3
author: "Alejandro Martín Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2023 Alejandro Martín Peralta Bazas"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aleperaltabazas/falzar/falzar-daemon#readme>

dependencies:
  - aeson <= 2.1.2.1
  - base >= 4.7 && < 5
  - bytestring <= 0.12.3
  - containers <= 0.6.7
  - falzar-commons
  - http-types <= 0.12.3
  - mtl <= 2.3.1
  - scotty <= 0.12.1
  - string-interpolate <= 0.3.2.1
  - transformers <= 0.6.1.1
  - text <= 2.0.2
  - wai <= 3.2.3
  - warp <= 3.3.28

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - QuasiQuotes
  - DeriveGeneric
  - OverloadedRecordDot

library:
  source-dirs: src

executables:
  falzar-daemon-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - falzar-daemon

tests:
  falzar-daemon-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - falzar-daemon
